# Generated by Django 6.0.3 on 2026-03-26 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('rojo', 'Rojo'), ('negro', 'Negro')], max_length=10, unique=True)),
                ('cantidad', models.IntegerField(default=0)),
            ],
        ),
    ]
