# Generated by Django 6.0.3 on 2026-03-30 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialColocacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('hilo', models.CharField(max_length=10)),
                ('cliente_de', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_colocacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fecha', '-hora'],
            },
        ),
    ]
