# Generated by Django 6.0.2 on 2026-02-26 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('auto', models.CharField(max_length=100)),
                ('hilo', models.CharField(choices=[('negro', 'Negro'), ('rojo', 'Rojo')], max_length=10)),
                ('atendido', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['fecha', 'hora'],
                'unique_together': {('fecha', 'hora')},
            },
        ),
    ]
