# Generated by Django 6.0.2 on 2026-02-26 16:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0002_turno_cliente_de_turno_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
