# Generated by Django 6.0.2 on 2026-02-26 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0003_alter_turno_precio'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='turno',
            unique_together=set(),
        ),
    ]
